'use client';
import {useEffect,useState} from 'react';
const SHOP='https://purekana.com/products/thc-sleep-gummies?variant=48855575068912';
const DEADLINE=new Date('2026-11-12T00:00:00-08:00');
const VIDEO='https://www.youtube.com/embed/Pj7OqIDjmEg?rel=0&modestbranding=1';
const copy={
  breaking:{eyebrow:'BREAKING CONSUMER ALERT',headline:'THE FEDERAL HEMP CLOCK IS RUNNING OUT',sub:'A new federal definition takes effect November 12, 2026 — and many hemp-derived THC products sold today may no longer qualify as hemp.',cta:'CHECK CURRENT AVAILABILITY',accent:'breaking'},
  investigation:{eyebrow:'SPECIAL INVESTIGATION',headline:'WHAT HAPPENS WHEN TODAY’S THC SLEEP GUMMIES NO LONGER FIT THE HEMP RULES?',sub:'Millions of adults built hemp-derived cannabinoids into nighttime routines. A federal change may sharply narrow what can still be sold as hemp.',cta:'SEE PUREKANA SLEEP GUMMIES',accent:'investigation'},
  deadline:{eyebrow:'THE NOVEMBER DEADLINE',headline:'THE WINDOW TO BUY TODAY’S HEMP THC FORMULAS MAY BE CLOSING',sub:'Congress changed the federal hemp definition. The effective date is November 12, 2026. Consumers are checking what is still available now.',cta:'SHOP BEFORE THE RULE CHANGE',accent:'deadline'}
};
function Countdown(){const[r,setR]=useState({days:'--',hours:'--',minutes:'--',seconds:'--'});useEffect(()=>{const tick=()=>{const d=Math.max(0,DEADLINE-Date.now());setR({days:Math.floor(d/86400000),hours:Math.floor(d/3600000)%24,minutes:Math.floor(d/60000)%60,seconds:Math.floor(d/1000)%60})};tick();const i=setInterval(tick,1000);return()=>clearInterval(i)},[]);return <div className="countdown">{Object.entries(r).map(([k,v])=><div className="count" key={k}><b>{String(v).padStart(2,'0')}</b><span>{k}</span></div>)}</div>}
function CTA({children}){return <a className="cta" href={SHOP} target="_blank" rel="noreferrer">{children}<span>→</span></a>}
export default function Advertorial({variant='breaking'}){const v=copy[variant];return <main className={`site ${v.accent}`}>
<div className="sponsor">SPONSORED CONSUMER REPORT • ADVERTISEMENT</div>
<header className="top"><div className="brand"><span>NEWS</span><i>at</i><b>10</b><small>.com</small></div><div className="live">● LIVE</div></header>
<div className="ticker"><b>CONSUMER ALERT:</b> Federal hemp rules change November 12, 2026.</div>
<section className="hero"><div className="heroInner"><span className="eyebrow">{v.eyebrow}</span><h1>{v.headline}</h1><p>{v.sub}</p><div className="aboveFold"><CTA>{v.cta}</CTA><small>Opens PureKana.com • Current availability may change</small></div><div className="byline">News at 10 Consumer Desk • Updated August 26, 2026 • Sponsored report</div></div></section>
<section className="videoWrap"><div className="videoHeader"><span>WATCH</span><b>Federal THC ban sends hemp companies scrambling</b></div><div className="videoFrame"><iframe src={VIDEO} title="Federal THC Ban Sends Hemp Companies Scrambling - The Hill" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe></div><p className="videoCredit">Video: The Hill • Embedded from YouTube</p><CTA>{v.cta}</CTA></section>
<section className="deadlineBar"><div><small>FEDERAL CHANGE TAKES EFFECT</small><strong>NOVEMBER 12, 2026</strong></div><Countdown/></section>
<div className="content"><article>
<p className="lede">For years, adults across the country have been able to buy hemp-derived THC products online under the federal hemp framework created after the 2018 Farm Bill. That framework is about to change.</p>
<h2>Congress changed what counts as “hemp.”</h2><p>The new federal definition moves toward a total-THC standard and excludes certain finished hemp-derived cannabinoid products from the definition of hemp. Federal materials state that finished products containing more than <b>0.4 milligrams of total THC per container</b> will be excluded.</p>
<div className="pull">“The change to the definition will seemingly alter the legal status of many hemp products currently available on the market.”<small>Congressional Research Service, discussing P.L. 119-37</small></div>
<h2>Why that matters for THC sleep gummies</h2><p>Many current hemp-derived THC gummies contain multiple milligrams of THC per serving, not per entire container. That puts the new threshold far below the THC content in many products currently sold online.</p>
<div className="warning"><b>WHAT CHANGES ON NOVEMBER 12</b><ul><li>A total-THC approach replaces today’s simpler delta-9 framework.</li><li>Finished cannabinoid products above 0.4 mg total THC per container are excluded from the federal hemp definition.</li><li>Many gummies currently sold as federally compliant hemp may be affected.</li><li>Availability after the effective date will also depend on enforcement and state law.</li></ul></div>
{variant==='investigation'&&<><h2>For sleep consumers, this is more than a technical policy fight.</h2><p>Adults who already use cannabinoid products as part of a nighttime routine may face fewer legal online options. These products are not approved treatments for insomnia and should not replace medical care, but access still matters to consumers who have chosen them as part of their routine.</p></>}
{variant==='deadline'&&<><h2>The most important thing consumers can do now is check availability.</h2><p>No one should assume a product that is easy to order today will remain available under the same federal framework after November 12.</p></>}
<section className="product"><div className="productVisual"><div className="moon">☾</div><div className="bag"><small>PURE</small><strong>KANA</strong><i>THC</i><b>SLEEP<br/>GUMMIES</b><span>HUCKLEBERRY</span></div></div><div className="productCopy"><span>CONSUMER SPOTLIGHT</span><h3>PureKana THC Sleep Gummies</h3><p>PureKana currently offers Sleep Gummies with hemp-derived THC, CBN and melatonin, with multiple THC strength options.</p><div className="facts"><b>20 gummies</b><b>Huckleberry</b><b>3rd-party tested</b></div><CTA>VIEW CURRENT AVAILABILITY</CTA><small>Availability, pricing and shipping eligibility may change.</small></div></section>
<h2>The date is real. The uncertainty is what comes next.</h2><p>Federal materials identify November 12, 2026 as the effective date. Industry groups are lobbying for changes and delays, so the policy landscape could still move. That is exactly why consumers and hemp businesses are watching the calendar closely.</p>
<div className="timeline"><div><b>2018</b><span>Farm Bill creates the modern federal hemp framework.</span></div><div><b>Nov. 12, 2025</b><span>New federal language changes the definition after a one-year transition.</span></div><div className="hot"><b>Nov. 12, 2026</b><span>New federal hemp definition is scheduled to take effect.</span></div></div>
<div className="finalCard"><span>THE WINDOW BEFORE NOVEMBER 12 IS GETTING SHORTER</span><h2>Check PureKana Sleep Gummies under today’s rules.</h2><Countdown/><CTA>{v.cta}</CTA></div>
<div className="disclaimer"><b>Transparency:</b> This is a paid advertorial, not an independent news report. Nothing here is legal or medical advice. Laws may change. THC can impair you and may cause a positive drug test. Keep away from children.</div>
</article><aside><div className="sideCard"><span>KEY FACT</span><b>0.4 mg</b><p>Total THC per container threshold in the new federal definition for finished hemp-derived cannabinoid products.</p></div><div className="sideCard danger"><span>DEADLINE</span><b>NOV 12</b><p>2026 scheduled effective date.</p></div><div className="sideBuy"><h3>Already use hemp THC for sleep?</h3><CTA>CHECK PUREKANA</CTA></div></aside></div>
<footer><div className="brand footerBrand"><span>NEWS</span><i>at</i><b>10</b><small>.com</small></div><p>Sponsored advertorial. Not affiliated with a television network or independent news organization.</p></footer>
<div className="sticky"><span>Hemp rules change Nov. 12, 2026</span><CTA>CHECK NOW</CTA></div>
</main>}
